services:
  nilcc-attester:
    image: ghcr.io/nillionnetwork/nilcc-attester@sha256:06c9ddf2969192aa0ed5e8773039acf84034ba19ea095c8e7886ff00e9dae5f9 # 0.4.0
    restart: unless-stopped
    privileged: true
    volumes:
      - "/dev/sev-guest:/dev/sev-guest"
    ports:
      - 80
    environment:
      APP__SERVER__BIND_ENDPOINT: "0.0.0.0:80"
      APP__NILCC_VERSION: ${NILCC_VERSION}
      APP__VM_TYPE: ${NILCC_VM_TYPE}
      APP__ATTESTATION_DOMAIN: ${NILCC_DOMAIN}
      NO_COLOR: 1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
    {DOCKER_COMPOSE_DEPLOY}

  nilcc-proxy:
    image: caddy@sha256:e9fd95fd7cea0c3403c622c5c2457cddcaf355a5eba11048b17cb3d99a828f33 # 2.10.2
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
    environment:
      CADDY_ACME_EAB_KEY_ID: ${CADDY_ACME_EAB_KEY_ID}
      CADDY_ACME_EAB_MAC_KEY: ${CADDY_ACME_EAB_MAC_KEY}
    volumes:
      - ${CADDY_INPUT_FILE}:/etc/caddy/Caddyfile
